/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.fj.struts.action;

import java.io.FileInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.fj.domain.Users;
import com.fj.service.UsersService;

/** 
 * MyEclipse Struts
 * Creation date: 04-15-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class DownFileAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		

		
		String username=request.getParameter("username");
		
		UsersService usersService=new UsersService();
		Users user=usersService.getUsersByName(username);
		
		
		String endname = "";
		try {
			endname = URLEncoder.encode(user.getPhotos2(),"utf-8");
		} catch (UnsupportedEncodingException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
//		告诉浏览器有下载文件
		response.setContentType("text/html;charset=utf-8");
		response.setHeader("Content-Disposition", "attachment; filename="+endname);
		
//		下面进行文件下载
//		得到文件的全路径
		String fileName=user.getPhotos();
		String allFileName=this.getServlet().getServletContext().getRealPath("/File");
		String filePath=allFileName+"//"+fileName;
		
		//System.out.println(filePath);
		
		FileInputStream fis=null;
		OutputStream os=null;
		try {
			fis=new FileInputStream(filePath);
			os=response.getOutputStream();
			
			int len=0;
			byte[] buf=new byte[1024];
			
			while((len=fis.read(buf))>0){
				os.write(buf, 0, len);
			}
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}finally{
			try {
				fis.close();
				
				
			} catch (Exception e2) {
				// TODO: handle exception
				e2.printStackTrace();
			}
		}
		
		return null;
	}
}