/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.fj.struts.action;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.fj.domain.Users;
import com.fj.service.UsersService;
import com.fj.struts.form.UserForm;
import com.fj.tools.FileClTool;

/** 
 * MyEclipse Struts
 * Creation date: 04-12-2017
 * 
 * XDoclet definition:
 * @struts.action path="/register" name="userForm" scope="request"
 */
public class RegisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		
		FormFile formFile=userForm.getMyphoto();
		String fileName=formFile.getFileName();
//		得到新的文件名
		FileClTool fileClTool=new FileClTool();
		String newName=fileClTool.getNewName(fileName);
		
		String keepFile=this.getServlet().getServletContext().getRealPath("/File");
		
		InputStream is=null;
		OutputStream os=null;
		//System.out.println(keepFile+"|"+fileName);
		try {
			is=formFile.getInputStream();
			os=new FileOutputStream(keepFile+"//"+newName);
			
			int len=0;
			byte[] buf=new byte[1024];
			
			while((len=is.read(buf))>0){
				os.write(buf,0,len);
			}
			
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}finally{
			try {
				is.close();
				os.close();
				
			} catch (Exception e2) {
				// TODO: handle exception
				e2.printStackTrace();
			}
		}
		
//		操作完成信息放入数据库
		UsersService usersService=new UsersService();
		Users user=new Users();
		user.setUsername(userForm.getName());
		user.setPhotos(newName);
		user.setPhotos2(fileName);
		if(usersService.addUser(user)){
			return mapping.findForward("ok");
		}else{
			return mapping.findForward("err");
		}
		
		
	}
}