/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.fj.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.fj.domain.Users;
import com.fj.service.UsersService;

/** 
 * MyEclipse Struts
 * Creation date: 04-14-2017
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UserListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		UsersService usersService=new UsersService();
		
		ArrayList<Users> al=usersService.getUserList();
//		for(Users user:al){
//			System.out.println(user.getUsername()+"   "+user.getPhotos()+"   "+user.getPhotos2());
//		}
		
		request.setAttribute("al", al);
		
		return mapping.findForward("gotoUserList");
	}
}